trigger:
  branches:
    include:
      - master
      - refs/tags/*

pr:
  autoCancel: true
  branches:
    include:
      - master

resources:
  repositories:
    - repository: rsg
      type: github
      name: RocketSurgeonsGuild/AzureDevopsTemplates
      # ref: refs/tags/v0.3.1
      endpoint: github

variables:
  Configuration: Release
  Verbosity: Normal
  DotNetVersion: "2.2.101"
  CakeVersion: "0.32.1"
  NuGetVersion: "4.9.2"
  Coverage: "$(Agent.BuildDirectory)/c"
  VstsCoverage: "$(Coverage)"
  Artifacts: $(Build.ArtifactStagingDirectory)
  VstsArtifacts: "$(Artifacts)"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"

jobs:
  - job: GitVersion
    pool:
      vmImage: vs2017-win2016
    steps:
      - template: gitversion/store.yml@rsg
        parameters:
          NuGetVersion: ${{ parameters.NuGetVersion }}

  - template: pipeline/cake-job.yml@rsg
    parameters:
      name: 'macOS'
      dependsOn: GitVersion
      vmImage: "macOS-10.13"
      pushNuget: false
      Configuration: ${{ parameters.Configuration }}
      Verbosity: ${{ parameters.Verbosity }}
      CakeVersion: ${{ parameters.CakeVersion }}
      DotNetVersion: ${{ parameters.DotNetVersion }}
      NuGetVersion: ${{ parameters.NuGetVersion }}
      Script: ${{ parameters.Script }}
      Target: ${{ parameters.Target }}

  - template: pipeline/cake-job.yml@rsg
    parameters:
      name: 'Linux'
      dependsOn: GitVersion
      vmImage: "Ubuntu-16.04"
      pushNuget: false
      Configuration: ${{ parameters.Configuration }}
      Verbosity: ${{ parameters.Verbosity }}
      CakeVersion: ${{ parameters.CakeVersion }}
      DotNetVersion: ${{ parameters.DotNetVersion }}
      NuGetVersion: ${{ parameters.NuGetVersion }}
      Script: ${{ parameters.Script }}
      Target: ${{ parameters.Target }}

  - template: pipeline/cake-job.yml@rsg
    parameters:
      name: 'Windows'
      dependsOn: GitVersion
      vmImage: "VS2017-Win2016"
      pushNuget: true
      Configuration: ${{ parameters.Configuration }}
      Verbosity: ${{ parameters.Verbosity }}
      CakeVersion: ${{ parameters.CakeVersion }}
      DotNetVersion: ${{ parameters.DotNetVersion }}
      NuGetVersion: ${{ parameters.NuGetVersion }}
      Script: ${{ parameters.Script }}
      Target: ${{ parameters.Target }}
